SELECT * FROM customer limit 20
--Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (
	SELECT AVG(purchase_amount) FROM customer
)
ORDER BY purchase_amount DESC


--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS Average_Product_Rating
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;


--Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) 
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS Total_customer,
ROUND(AVG(purchase_amount),2) as Avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
Group BY subscription_status
order BY total_revenue, avg_spend desc;


--Q6. Which 5 products have the hightest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as Discount_rate
FROM customer
group by item_purchased
order by 2 desc
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchase and show
-- the count of each segment
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 then 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END customer_segment
FROM customer 
)
SELECT customer_segment, COUNT(*) AS "Number of Customer"
from customer_type
GROUP BY customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased, COUNT(customer_id) total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) item_rank
from customer
group by category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9 Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) Repeat_buyers
FROM customer
WHERE previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
SELECT age, 
SUM(purchase_amount) Total_revenue
from customer
group by age
order by 2 desc;